export const ContactDetailsData = {
  Strings: {
    firstNameEdited: "Edited",
    lastNameEdited: "Edited",
    dateOfBirthEdited: "1800-10-12",
    emailFieldEdited: "edited@edited.com",
    phoneEdited: "000000",
    street1Edited: "edited1",
    street2Edited: "edited2",
    cityEdited: "edited",
    stateEdited: "edited",
    postalEdited: "99999",
    countryEdited: "edited",
  },

  Locators: {
    editContactBtn: "#edit-contact",
    deleteContactBtn: "#delete",
    returnBtn: "#return",
    firstName: "#firstName",
    lastName: "#lastName",
    dateOfBirth: "#birthdate",
    emailField: "#email",
    phone: "#phone",
    street1: "#street1",
    street2: "#street2",
    city: "#city",
    state: "#stateProvince",
    postal: "#postalCode",
    country: "#country",
    submitBtn: "#submit",
    cancelBtn: "#cancel",
  },
};
